### ISSUE TITLE
NullReferenceException during download (v1.11.1)

### ISSUE THREAD

**Issue by SectOLT** [GuVAnj8Gv3RJ/NeosAccountDownloader#223] opened 2023-09-21 23:46 UTC
Not much to comment on here.

The download was happening normally until during one of the records fetching, an error popped up, which halted the whole process.
It is speculated that the error happened due to a side effect on Neos' end, but the tool couldn't handle it.

```
2023-09-21 19:35:23.005 -04:00 [ERR] Object reference not set to an instance of an object.
2023-09-21 19:35:23.164 -04:00 [ERR] System.NullReferenceException: Object reference not set to an instance of an object.
   at AccountDownloaderLibrary.LocalAccountDataStore.<InitDownloadProcessor>b__34_0(AssetJob job)
   at AccountDownloaderLibrary.LocalAccountDataStore.Complete()
   at AccountDownloaderLibrary.AccountDownloadController.Download(CancellationToken cancellationToken)
2023-09-21 19:35:23.164 -04:00 [INF] Download Report
----------------------
Contacts: 680 / 680
Messages: 1106
Assets: 457/ 13552
Downloaded Definitions: 0
Downloaded Variable Value Count: 111
Records: 1748 / 1748
Failed: 0

7650 Assets were skipped because they were already downloaded.
Error: Object reference not set to an instance of an object.
```

Unless there is a way to gather more info on the matter, it's all the logs managed to catch

**Comment by Nytra** [comment] 2023-09-21 23:55
Duplicate of #202 ?

**Comment by SectOLT** [comment] 2023-09-21 23:58
Indeed my bad, did not see that other one.

**Closed** 2023-09-22 00:02 UTC

**Comment by GuVAnj8Gv3RJ** [comment] 2023-09-22 02:14
@all-contributors please add @SectOLT for bugs
