### ISSUE TITLE
Log File Does Not Report Assets Count or Asset Download Errors

### ISSUE THREAD

**Issue by stiefeljackal** [GuVAnj8Gv3RJ/NeosAccountDownloader#65] opened 2023-07-26 18:37 UTC
When completing the download, the tool reported that 59 assets were missing (Assets: 17564 / 17623).

<img width="612" alt="image" src="https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/20023996/a7bc5e45-89e6-4c32-815f-356e972fbb5a">

Due to this, I checked the logs to see which assets it had failed to download. However, I could not find any sort of errors reported. Thinking that this was perhaps an incorrect number being reported, I looked at the bottom of the log for the count when I realized that it is missing.

![image](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/20023996/d1fef989-f78c-48f2-be0b-8fc93ad3d6a5)

I believe the count should be recorded in the log as it is also shown in the application (see the first image). Additionally, I understand the disclaimer that the tool may be unable to download everything from my account. However, if the tool is reporting assets that it had found, then it should state a warning or error about retrieving that asset instead of silently ignoring the issue. I know this sort of thing would not be acceptable by many Neos groups.

**Comment by GuVAnj8Gv3RJ** [comment] 2023-07-27 02:53
You're meant to see this:
![image](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/132167543/0234002a-7e3f-41ee-8dd1-fb4f41ae81bb)


In the UI which took... forever to write... :'(

I'll see about figuring out why BOTH are broken :'(

**Comment by GuVAnj8Gv3RJ** [comment] 2023-07-27 04:49
Alright much better: 
![image](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/132167543/515c9ba8-8652-43e4-894a-29071de42dd2)

Time to use the above UI to display info aswell. GridViews are not fun.

**Comment by stiefeljackal** [comment] 2023-07-27 05:07
I agree. It's like HTML tables. Not fun.

**Comment by GuVAnj8Gv3RJ** [comment] 2023-07-27 05:27
Fixed in #69 , probably needs a bunch of UI tweaks but those can happen later. PR for timeout issue coming soon(90% of asset failures are caused by this)

**Closed by GuVAnj8Gv3RJ** 2023-07-27 05:27 UTC
